// Code generated by internal/telemetry/gen from telemetry/registry. DO NOT EDIT.

package telemetry

// Attribute names: ynf's own, then the OpenTelemetry attributes it uses.
const (
	// The work item's store key (ADR-002). Never on a metric.
	AttrItemKey = "ynf.item.key"
	// The step's id, which names its side effects (ADR-005). Never on a metric.
	AttrStepID = "ynf.step.id"
	// The run's id, the step id and the run's number within the step. Never on a metric.
	AttrRunID = "ynf.run.id"
	// The lane's id: where the lane is defined, host first, then its name, or the lane's own explicit id. ynr stamps it on a run's records from ynf's run manifest, on ynf's behalf.
	AttrLane = "ynf.lane"
	// The harness the run actually used, so a repository that overrides a lane shows as a variant of the same factory. ynr stamps it from ynf's run manifest, on ynf's behalf.
	AttrLaneHarness = "ynf.lane.harness"
	// The focus the run actually used. ynr stamps it from ynf's run manifest, on ynf's behalf.
	AttrLaneFocus = "ynf.lane.focus"
	// The SHA-256 of the lane's normalised form, recorded with every decision (ADR-006).
	AttrPolicyHash = "ynf.policy.hash"
	// The epoch of the lease the step holds (ADR-005).
	AttrLeaseEpoch = "ynf.lease.epoch"
	// The repository the work's code goes to, in ynf's host-first form.
	AttrRepo = "ynf.repo"
	// The state the decision left the item in (ADR-006).
	AttrItemState = "ynf.item.state"
	// The kind of action a decision asked for (ADR-006).
	AttrAction = "ynf.action"
	// ynf's own outcome for a unit of work, which also sets the span's status.
	AttrOutcome = "ynf.outcome"
	// What ynf did with a CloudEvent it received.
	AttrIntakeResult = "ynf.intake.result"
	// The other system a call went to.
	AttrCallSystem = "ynf.call.system"
	// What the call did, such as pull_request or push. Never a name or text from the system.
	AttrCallOperation = "ynf.call.operation"
	// Which tokens a count is of.
	AttrTokenType = "ynf.token.type"
	// What kind of actor the handle in user.name names.
	AttrActorKind = "ynf.actor.kind"
	// Whether a lane control paused the lane (true) or resumed it (false).
	AttrPaused                  = "ynf.paused"
	AttrCloudeventsEventID      = "cloudevents.event_id"
	AttrCloudeventsEventSource  = "cloudevents.event_source"
	AttrCloudeventsEventSubject = "cloudevents.event_subject"
	AttrCloudeventsEventType    = "cloudevents.event_type"
	AttrGenAiResponseModel      = "gen_ai.response.model"
	AttrVcsRepositoryURLFull    = "vcs.repository.url.full"
)

// Span names.
const (
	// One step on one item (ADR-001), the root of the step's trace.
	SpanStep = "ynf.step"
	// Taking the item's lease.
	SpanClaim = "ynf.claim"
	// Reading the facts a decision needs from the ticket and the forge.
	SpanProbe = "ynf.probe"
	// The decider reading the item, the facts and the lane, and what it chose.
	SpanDecide = "ynf.decide"
	// One action a decision asked for.
	SpanAct = "ynf.act"
	// One run of a lane's runner on a worktree.
	SpanRun = "ynf.run"
	// A CloudEvent ynf received, recorded so a step can link to it (ynr ADR-003).
	SpanIntake = "ynf.intake"
	// A call out to another system: a forge, a tracker, git, ynm, docker or an executor.
	SpanCall = "ynf.call"
	// A person pausing or resuming a lane.
	SpanLaneControl = "ynf.lane.control"
)

// Event names.
const (
	// A step began. A start with no matching span is how a crash shows.
	EventStepStarted = "ynf.step.started"
	// A run began.
	EventRunStarted = "ynf.run.started"
	// The decider chose. Its reasoning is in ynf's store, never in telemetry.
	EventDecisionMade = "ynf.decision.made"
	// A CloudEvent ynf received, written once inside its ynf.intake span: the one-way mirror of the control plane into telemetry. Nothing in ynf reads telemetry.
	EventIntakeReceived = "ynf.intake.received"
)

// Metric names.
const (
	// Runs, by outcome, lane and model.
	MetricRunCount = "ynf.run.count"
	// Tokens runs used, by model and kind, as the runner reports them.
	MetricRunTokens = "ynf.run.tokens"
	// What runs cost, by model, as the runner reports it. ynf never prices tokens itself.
	MetricRunCost = "ynf.run.cost"
	// Leases found expired when a step claimed the item, so a holder died or stalled.
	MetricLeaseExpired = "ynf.lease.expired"
)

// Values of ynf.outcome.
const (
	// A run: the lane's sensors passed.
	OutcomeConverged = "converged"
	// A run: a cap ended it.
	OutcomeBudget = "budget"
	// A run: it stopped making progress.
	OutcomeStuck = "stuck"
	// A run: it changed what it must not.
	OutcomeTamper = "tamper"
	// A run: the operator's setup refused or broke it.
	OutcomeOperatorError = "operator_error"
	// A run: ynf or the runner failed.
	OutcomeError = "error"
	// A run: it was stopped.
	OutcomeAborted = "aborted"
	// A step: it ran to the point the item waits.
	OutcomeCompleted = "completed"
	// A step, phase or call: it ended in an error.
	OutcomeFailed = "failed"
	// A step: its lease was lost, so it stopped.
	OutcomeLost = "lost"
	// A step or claim: another instance holds the item.
	OutcomeHeld = "held"
	// A claim: the lease was taken.
	OutcomeClaimed = "claimed"
	// A phase or call: it succeeded.
	OutcomeOk = "ok"
	// An intake: the event was taken in.
	OutcomeAccepted = "accepted"
	// An intake: the event had been received before.
	OutcomeDeduplicated = "deduplicated"
	// An intake: the event was refused.
	OutcomeRejected = "rejected"
)

// Values of ynf.intake.result.
const (
	// The event was taken in.
	IntakeResultAccepted = "accepted"
	// The event had been received before.
	IntakeResultDeduplicated = "deduplicated"
	// The event was refused.
	IntakeResultRejected = "rejected"
)

// Values of ynf.call.system.
const (
	// A forge, such as GitHub.
	CallSystemForge = "forge"
	// A tracker.
	CallSystemTracker = "tracker"
	// Git, on the host.
	CallSystemGit = "git"
	// ynm, ynf's memory.
	CallSystemYnm = "ynm"
	// Docker, where an agent image is made.
	CallSystemDocker = "docker"
	// The executor that runs a lane's command.
	CallSystemExecutor = "executor"
	// ynh, where it builds an agent image.
	CallSystemYnh = "ynh"
)

// Values of ynf.token.type.
const (
	// Input tokens.
	TokenTypeInput = "input"
	// Output tokens.
	TokenTypeOutput = "output"
	// Tokens read from a cache.
	TokenTypeCacheRead = "cache_read"
)

// Values of ynf.actor.kind.
const (
	// A person.
	ActorKindHuman = "human"
	// Another automation.
	ActorKindBot = "bot"
	// ynf itself.
	ActorKindYnf = "ynf"
)

// CardinalityLimits is the most distinct values each metric attribute may take, from the
// registry's ynr.cardinality annotations.
var CardinalityLimits = map[string]int{
	"gen_ai.response.model": 50,
	"ynf.lane":              100,
	"ynf.outcome":           20,
	"ynf.token.type":        3,
}
