package registry

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"strings"
	"unicode"
)

// Generate writes the Go constants for a registry: one for every attribute, span, event and metric
// name, and one for every value of an enumerated attribute. Code uses these and never a string
// literal, so a name that is not in the registry does not compile.
func Generate(r *Registry, pkg string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/telemetry/gen from telemetry/registry. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	b.WriteString("// Attribute names: ynf's own, then the OpenTelemetry attributes it uses.\nconst (\n")
	for _, a := range r.Attributes {
		fmt.Fprintf(&b, "\t// %s\n\tAttr%s = %q\n", oneLine(a.Brief), goName(a.ID), a.ID)
	}
	for _, id := range r.Standard {
		fmt.Fprintf(&b, "\tAttr%s = %q\n", goName(id), id)
	}
	b.WriteString(")\n\n")

	b.WriteString("// Span names.\nconst (\n")
	for _, s := range r.Spans {
		fmt.Fprintf(&b, "\t// %s\n\tSpan%s = %q\n", oneLine(s.Brief), goName(s.Name), s.Name)
	}
	b.WriteString(")\n\n")

	b.WriteString("// Event names.\nconst (\n")
	for _, e := range r.Events {
		fmt.Fprintf(&b, "\t// %s\n\tEvent%s = %q\n", oneLine(e.Brief), goName(e.Name), e.Name)
	}
	b.WriteString(")\n\n")

	b.WriteString("// Metric names.\nconst (\n")
	for _, m := range r.Metrics {
		fmt.Fprintf(&b, "\t// %s\n\tMetric%s = %q\n", oneLine(m.Brief), goName(m.Name), m.Name)
	}
	b.WriteString(")\n\n")

	for _, a := range r.Attributes {
		if len(a.Members) == 0 {
			continue
		}
		fmt.Fprintf(&b, "// Values of %s.\nconst (\n", a.ID)
		for _, m := range a.Members {
			fmt.Fprintf(&b, "\t// %s\n\t%s%s = %q\n", oneLine(m.Brief), goName(a.ID), goName(m.ID), m.Value)
		}
		b.WriteString(")\n\n")
	}

	// The limits a metric attribute may reach, as the registry declares them.
	limits := map[string]int{}
	for _, m := range r.Metrics {
		for _, u := range m.Attributes {
			if u.Cardinality > 0 {
				limits[u.Name] = max(limits[u.Name], u.Cardinality)
			}
		}
	}
	names := make([]string, 0, len(limits))
	for n := range limits {
		names = append(names, n)
	}
	slices.Sort(names)
	b.WriteString("// CardinalityLimits is the most distinct values each metric attribute may take, from the\n// registry's ynr.cardinality annotations.\nvar CardinalityLimits = map[string]int{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t%q: %d,\n", n, limits[n])
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

// goName turns a registry name into an exported Go identifier: ynf.item.key is ItemKey,
// cloudevents.event_id is CloudeventsEventID. The prefix ynf. is dropped.
func goName(id string) string {
	id = strings.TrimPrefix(id, "ynf.")
	var b strings.Builder
	for _, w := range strings.FieldsFunc(id, func(r rune) bool { return r == '.' || r == '_' || r == '-' }) {
		switch w {
		case "id":
			b.WriteString("ID")
		case "url":
			b.WriteString("URL")
		default:
			rs := []rune(w)
			rs[0] = unicode.ToUpper(rs[0])
			b.WriteString(string(rs))
		}
	}
	return b.String()
}

func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }
